### PR TITLE
Task3951

### PR DESCRIPTION
**Pull request by michaelpace-bjss**
Data model changes for 
Split suppliers from Organisation
Pricing 
Removed user and team tables

### CODE REVIEW

**Review by michaelpace-bjss — COMMENTED** [review]
Changes reviewed and approved

**Review by michaelpace-bjss — COMMENTED** [review]
Review and approved

**Review by michaelpace-bjss — COMMENTED** [review]
Alteration for docker approved

**Review by sam-roberts-bjss — APPROVED** [review]
👍

**Pull request merged**
